/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupProfileRouteImport } from './routes/setup-profile'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedProfileRouteImport } from './routes/authenticated/profile'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/authenticated/groups/index'
import { Route as AuthenticatedGroupsIdIndexRouteImport } from './routes/authenticated/groups/$id/index'
import { Route as AuthenticatedGroupsIdSettingsRouteImport } from './routes/authenticated/groups/$id/settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProfileRoute = SetupProfileRouteImport.update({
  id: '/setup-profile',
  path: '/setup-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/authenticated/profile',
  path: '/authenticated/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/authenticated/groups/',
    path: '/authenticated/groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGroupsIdIndexRoute =
  AuthenticatedGroupsIdIndexRouteImport.update({
    id: '/authenticated/groups/$id/',
    path: '/authenticated/groups/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGroupsIdSettingsRoute =
  AuthenticatedGroupsIdSettingsRouteImport.update({
    id: '/authenticated/groups/$id/settings',
    path: '/authenticated/groups/$id/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/setup-profile': typeof SetupProfileRoute
  '/signup': typeof SignupRoute
  '/authenticated/profile': typeof AuthenticatedProfileRoute
  '/authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/authenticated/groups/$id/settings': typeof AuthenticatedGroupsIdSettingsRoute
  '/authenticated/groups/$id/': typeof AuthenticatedGroupsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/setup-profile': typeof SetupProfileRoute
  '/signup': typeof SignupRoute
  '/authenticated/profile': typeof AuthenticatedProfileRoute
  '/authenticated/groups': typeof AuthenticatedGroupsIndexRoute
  '/authenticated/groups/$id/settings': typeof AuthenticatedGroupsIdSettingsRoute
  '/authenticated/groups/$id': typeof AuthenticatedGroupsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/setup-profile': typeof SetupProfileRoute
  '/signup': typeof SignupRoute
  '/authenticated/profile': typeof AuthenticatedProfileRoute
  '/authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/authenticated/groups/$id/settings': typeof AuthenticatedGroupsIdSettingsRoute
  '/authenticated/groups/$id/': typeof AuthenticatedGroupsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/otp'
    | '/setup-profile'
    | '/signup'
    | '/authenticated/profile'
    | '/authenticated/groups/'
    | '/authenticated/groups/$id/settings'
    | '/authenticated/groups/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/otp'
    | '/setup-profile'
    | '/signup'
    | '/authenticated/profile'
    | '/authenticated/groups'
    | '/authenticated/groups/$id/settings'
    | '/authenticated/groups/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/otp'
    | '/setup-profile'
    | '/signup'
    | '/authenticated/profile'
    | '/authenticated/groups/'
    | '/authenticated/groups/$id/settings'
    | '/authenticated/groups/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  SetupProfileRoute: typeof SetupProfileRoute
  SignupRoute: typeof SignupRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedGroupsIdSettingsRoute: typeof AuthenticatedGroupsIdSettingsRoute
  AuthenticatedGroupsIdIndexRoute: typeof AuthenticatedGroupsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-profile': {
      id: '/setup-profile'
      path: '/setup-profile'
      fullPath: '/setup-profile'
      preLoaderRoute: typeof SetupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/profile': {
      id: '/authenticated/profile'
      path: '/authenticated/profile'
      fullPath: '/authenticated/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/groups/': {
      id: '/authenticated/groups/'
      path: '/authenticated/groups'
      fullPath: '/authenticated/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/groups/$id/': {
      id: '/authenticated/groups/$id/'
      path: '/authenticated/groups/$id'
      fullPath: '/authenticated/groups/$id/'
      preLoaderRoute: typeof AuthenticatedGroupsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/groups/$id/settings': {
      id: '/authenticated/groups/$id/settings'
      path: '/authenticated/groups/$id/settings'
      fullPath: '/authenticated/groups/$id/settings'
      preLoaderRoute: typeof AuthenticatedGroupsIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  SetupProfileRoute: SetupProfileRoute,
  SignupRoute: SignupRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedGroupsIdSettingsRoute: AuthenticatedGroupsIdSettingsRoute,
  AuthenticatedGroupsIdIndexRoute: AuthenticatedGroupsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
